config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   root to:'events#index'

  #get 'events/index'
  
  
  resources :users, only: [:show]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	
	belongs_to :user, required: false
    belongs_to :event, required: false

end

app/models/event.rb
class Event < ApplicationRecord

	has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: "User", required: false

	validates :start_date, presence: true 
    validate :start_date_not_before_time_now
    validates :duration, presence: true, :numericality => { greater_than: 0 }
    validate :duration_minutes 
	validates :title, presence: true, length: { in: 5..140, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 20..1000, message: "Un description fait entre 20 et 1000 caractères" }
	validates :price, presence: true, length: { in: 1..1000, message: "Le prix doit etre compris entre 1 et 1000 €" } 
	validates :location, presence: true 


	def start_date_not_before_time_now #Méthode pour ne pas entrer une date antérieur à la date de debut 
	    if start_date < Date.today
            errors.add(:start_date, "la date ne doit pas etre dans le passé") 
        end  
    end

    def duration_minutes #met l'entre de duree de l'even en positif multiple de 5
        unless duration.present? && duration > 0 && duration % 5 == 0
            errors.add(:duration, "la durée doit etre positive et multiple de 5")
          end
     end

end

	#def start_date_not_before_time_now
    	#unless start_date.present? && start_date > DateTime.now
      		#errors.add(:start_date, "La date ne peut pas etre inférieure à aujourd'hui")
    	#end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	#has_many :attendances
	#has_many :events, foreign_key: 'admin_id', class_name: "Event"

	has_many :events, through: :attendances 
  has_many :events, foreign_key: 'admin_id', class_name: "User"
   

   after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end




# Un utilisateur peut participer à plusieurs événements au travers des participations. 
# Un utilisateur peut administrer plusieurs événements.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
  def index #rechercher les bases de fichier & seed
    @list_events = Event.all
  end

  def create
  end

  def show
    @event_searched = Event.find(params[:id])
  end

  def new 
    @event = Event.new
end
 def create
    @event = Event.new('title' => params[:event_title], 'location' => params[:event_location], 'description' => params[:event_description], 'start_date' => params[:event_date], 'price' => params[:event_price].to_i, 'duration' => params[:event_duration].to_i)
    @event.admin = current_user
    
    if @event.save
      redirect_to events_path, notice: "L'événement #{@event.title} a bien été créé ! Bien joué petit génie !"
    else
      redirect_to new_event_path, alert: "Certaines informations sont incorrectes : la description doit faire au moins 20 caractères et la date doit être dans le futur. "
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_current_user
  
    def show
      @event = Event.find(params[:id])
      puts @event
    end
  
    private
  
    def authenticate_current_user
      unless current_user == User.find(params[:id])
        redirect_to events_path, alert: "Vous ne pouvez pas accéder à cette page"
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Eventbrite - Home</title>
    </head>

    
  <body>
  
  <main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron" 
    <div class="container">
      <h1 class="display-3">Bienvenue sur Event Brite </h1>
      <p>Decouvrez tous les evenements autour de vous</p>
      <p><%= button_to "Crée un événement", new_event_path, class:"btn btn-primary btn-lg", :method => :get %></p>
    </div>
  </div>

  <center>

  <div class="all_events_title">
      <h1 style="font-size:40px;" >Tous les events </h1></br></br>
  </div>
  

 <div class="container" id="events_container"> 
  <div class="list-group">
   <% @list_events.each do |event| %>
    <%= link_to events_path(event.id), class: "list-group-item-action" do %>
      <div class="event_description">  
        <div class="text-center">
            <h5 class="mb-2">Event n°<%= event.id %> : <%= event.title %></h5></br>            
        </div> 
            <p class="mb-2"><%= event.description %></p>

      </div>
      <% end %>
   <% end %>
  </div>
</div>
 
</center> 
  </body>
 
</html>

app/views/events/new.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Créer un événement</title>
  </head>
<body>
  <!-- Message d'erreur en cas de problème-->
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <p>Nous n'avons pas réussi à créer l'event pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
          <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Formulaire création évènement -->
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">  
        <br><br><br>
        <h1>Création événement</h1>

        <%= form_tag url_for(action: 'create'), method: "post" do %>
          
          <div class="form-group">
            <label for="formGroupExampleInput">Renseigne un titre:</label>
            <input type="text" class="form-control" id="event_title" placeholder="Titre">
          </div>

          <div class="form-group">
            <label for="formGroupExampleInput">Indique un lieu:</label>
            <input type="text" class="form-control" id="event_location" placeholder="Lieu">
          </div>

          <div class="form-group">
            <label for="exampleFormControlTextarea1">Met ta description:</label>
            <textarea class="form-control" id="event_description" rows="3"></textarea>
          </div>

          <div class="form-group">
            <label for="formGroupExampleInput">Indique une date:</label>
            <input type="date" class="form-control" id="event_date">
          </div>
          
          <div class="form-group">
            <label for="formGroupExampleInput">Balance un prix:</label>
            <input type="integer" class="form-control" id="event_price" placeholder="Prix">
          </div>

          <div class="form-group">
            <label for="formGroupExampleInput">Complète avec une durée (en minutes, multiple de 5):</label>
            <input type="integer" class="form-control" id="event_duration" placeholder="Durée">
          </div>

          <div class="actions mt-5">
            <%= submit_tag("Créer Event", :class =>"btn btn-primary") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/events/show.html.erb
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>The Evenbrides App - Événement</title>
</head>

<body>

    <div class="container" style= "margin-bottom: 45px">
        <div class="row">
            <div class="col-sm-12 ">
                <h2 class="card-title "> Événement <%=@event.title%></h2>
                
                <p>Date de début : <%=@event.start_date %></p>
                <p>Lieu :: <%= @event.location %></p>
                <p>Durée : <%=@event.duration %> minutes</p>
                <p>Prix : <%= @event.price %>€</p>
                <p>Description : <%= @event.description %></p>

                <p><%= @event.attendances.count %> <%= (@event.attendances.count) == 1 ? 'Participant' : 'Participants'%></p>

                <%= button_to 'Participez !', events_path, method: :post %>
            </div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Eventbrite - accueil</title>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'EVENT BRITE', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
           <%= link_to 'Accueil', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to 'Créer un event', new_event_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Se connecter
          </a>
          <div class="dropdown-menu">
    <form class="px-4 py-3">
      <div class="form-group">
        <label for="exampleDropdownFormEmail1">Adresse email</label>
        <input type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
      </div>
      <div class="form-group">
        <label for="exampleDropdownFormPassword1">Mot de passe</label>
        <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="dropdownCheck">
        <label class="form-check-label" for="dropdownCheck">
          se rappeler de moi
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Se connecter</button>
    </form>
    <div class="dropdown-divider"></div>
     <%= link_to "Pas encore de compte ? Inscrivez-vous", new_user_registration_path, class: "dropdown-item" %>
    <%= link_to "Mot de passe oublié ?", new_user_session_path, class: "dropdown-item" %>
  </div>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>The Evenbrides App - User</title>
    </head>

    <body>
        <div class="container" style= "margin-bottom: 45px">
            <div class="row">
                <h1>Page Profil</h1>
                <div class="col-sm-12 ">
                    <h2 class="card-title "> Profil <%=@user.first_name%></h2>
                    
                    <%if @user.avatar.attached?%>
                        <%= image_tag @user.avatar, alt: 'avatar' %>
                    <%else%>
                        <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
                    <%end%>

                    <p>Prénom : <%=@user.first_name %></p>
                    <p>Nom : <%=@user.last_name %></p>
                    <p>Description : <%= @user.description %></p>
                    <p>Email : <%= @user.email %></p>
                    
                </div>
                <div class = mt->
                    <h5>Changer d'avatar ?</h5>
                    <%= form_tag user_avatars_path(@user), multipart: true do %>
                        <%= file_field_tag :avatar %>
                        <%= submit_tag "mettre à jour" %>
                    <% end %>
                </div>

            </div>
        </div>
        
        <div class="container" style= "margin-bottom: 25px">
            <div class="row">
                <div class="col-sm-12">
                    <h4>Mes évènements à venir :</h4>
                </div>
                <div class="col-sm-12 ">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Evénement</th>
                            <th scope="col">Page de l'événément</th>
                        </tr>
                        </thead>
                        <tbody>
                            <% @user_events_attendances.each do |event| %>
                                <% if event.start_date > Date.today  %>
                                    <tr>
                                        <td><%=event.title %></td>
                                        <td><%= link_to 'Détail', event_path(event.id), class: 'btn btn-secondary bg-info' %></td>
                                    </tr>
                                    <tr>
                                <% end %>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <h4>Mes événements en tant qu'organisateur:</h4>
                </div>
                <div class="col-sm-12 ">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Evénement</th>
                            <th scope="col">Page de l'événément</th>
                        </tr>
                        </thead>
                        <tbody>
                            <% @user_events_admin.each do |event| %>
                        <tr>
                            <td><%=event.title %></td>
                            <td><%= link_to "Voir plus", event_path(event.id) %></td>
                        </tr>
                        <tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>